# Generated by Django 4.2.14 on 2024-07-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterbikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
