# Generated by Django 4.2.14 on 2024-07-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterbikes', '0002_alter_bicicleta_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_solicitud',
        ),
    ]
