# Generated by Django 4.2.14 on 2024-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterbikes', '0003_rename_fecha_reserva_reserva_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='entregada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='En camino', max_length=50),
        ),
    ]
